apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-e5db755f-3903-48e2-8962-b2f217ef0b9d
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: local-mongodb
    namespace: mongodb
  hostPath:
    path: /var/local-path-provisioner/pvc-e5db755f-3903-48e2-8962-b2f217ef0b9d_mongodb_local-mongodb
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - challange-control-plane
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
