apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-ae500904-61c8-4676-9364-87af81e59e57
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-local-postgres-postgresql-0
    namespace: postgres
  hostPath:
    path: /var/local-path-provisioner/pvc-ae500904-61c8-4676-9364-87af81e59e57_postgres_data-local-postgres-postgresql-0
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - challange-control-plane
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
