apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homepage-application-set
  namespace: argocd
spec:
  template:
    metadata:
      name: '{{cluster}}-homepage'
    spec:
      source:
        repoURL: https://jameswynn.github.io/helm-charts
        targetRevision: 1.2.3
        chart: homepage
        valueFiles:
        - values.yaml
        - ingress.yaml

