apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: emqx-application-set
  namespace: argocd
spec:
  template:
    metadata:
      name: '{{cluster}}-emqx'
    spec:
      source:
        repoURL: https://jameswynn.github.io/helm-charts
        targetRevision: 0.9.2
        chart: homepage
