apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homepage-application-set
  namespace: argocd
spec:
  template:
    metadata:
      name: '{{cluster}}-homepage'
    spec:
      sources:
      - repoURL: https://jameswynn.github.io/helm-charts
        targetRevision: 1.2.3
        chart: homepage
        helm:
          valueFiles:
          -  $values/application-sets/homepage/values.yaml
      - repoURL: https://github.com/MSBarbieri/argocd-application-sets.git
        targetRevision: HEAD
        ref: values
