apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homepage-application-set
  namespace: argocd
spec:
  template:
    metadata:
      name: '{{cluster}}-homepage'
    spec:
      source:
        repoURL: https://jameswynn.github.io/helm-charts
        targetRevision: 1.2.3
        chart: homepage
        helm:
          valuesObject:
            ######################################################
            config:
              background:
                image: https://raw.githubusercontent.com/MSBarbieri/wallpapers/main/wallpapers/Pictures/wallpapers/spike_bebop.jpg?raw=true
                blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
                saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
                brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
                opacity: 50 # 0-100
              bookmarks:
                - Developer:
                    - Github:
                        - abbr: GH
                          href: https://github.com/
                    - Gitlab:
                        - abbr: GL
                          href: http://gitlab.colmeia.me/
              services:
                - ArgoCD:
                    - My Third Service:
                        href: https://argocd.kube.msbarbieri.dev/
                        description: Homepage is 😎
              widgets:
                # show the kubernetes widget, with the cluster summary and individual nodes
                - kubernetes:
                    cluster:
                      show: true
                      cpu: true
                      memory: true
                      showLabel: true
                      label: "cluster"
                    nodes:
                      show: true
                      cpu: true
                      memory: true
                      showLabel: true
                - search:
                    provider: google
                    target: _blank
              kubernetes:
                mode: cluster
            # The service account is necessary to allow discovery of other services
            serviceAccount:
              create: true
              name: homepage

            # This enables the service account to access the necessary resources
            enableRbac: true
            ingress:
              main:
                enabled: true
                annotations:
                  # Example annotations to add Homepage to your Homepage!
                  gethomepage.dev/enabled: "true"
                  gethomepage.dev/name: "Homepage"
                  gethomepage.dev/description: "Dynamically Detected Homepage"
                  gethomepage.dev/group: "Dynamic"
                  gethomepage.dev/icon: "homepage.png"
                  traefik.ingress.kubernetes.io/router.entrypoints: websecure
                  traefik.ingress.kubernetes.io/router.tls: 'true'
                  ingress.kubernetes.io/force-ssl-redirect: "true"
                tls:
                  - secretName: istio-cert
                    hosts:
                    -  kube.msbarbieri.dev
                hosts:
                  - host: kube.msbarbieri.dev
                    paths:
                      - path: /
                        pathType: Prefix
