apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homepage-application-set
  namespace: argocd
spec:
  template:
    metadata:
      name: '{{cluster}}-homepage'
    spec:
      source:
        repoURL: https://jameswynn.github.io/helm-charts
        targetRevision: 1.2.3
        chart: homepage
        helm:
          valuesObject:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: latest
            config:
              settings:
                title: Matheus Barbieri HomePage
                background:
                  image: https://github.com/MSBarbieri/wallpapers/blob/ee3f94dd71e228412ab83991c609fa9afeb23cba/mylivewallpapers-com-Miyamoto-Vagabond-4K-ezgif.com-video-to-webp-converter.webp?raw=true
                  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
                  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
                  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
                  opacity: 50 # 0-100
                headerStyle: clean
                target: _self
                quicklaunch:
                  searchDescriptions: true
                  hideInernetSearch: true
                  showSearchSuggestions: true
                  provider: google
                statusStyle: "dot"
                layout:
                  Colmeia:
                    style: row
                    columns: 4
                  Colmeia Admin:
                    style: row
                    columns: 2
                  Colmeia Management:
                    style: row
                    columns: 2
                  HomeLab:
                    style: row
                    columns: 2
                    header: false
                  Media:
                    style: row
                    columns: 4


              bookmarks:
                - Developer:
                    - Github:
                        - abbr: gh
                          href: https://github.com/
                    - Gitlab:
                        - abbr: gl
                          href: http://gitlab.colmeia.me/
                    - Google Cloud:
                        - abbr: gcp
                          href: https://console.cloud.google.com/
              services:
                - Personal:
                    - ArgoCD:
                        href: https://argocd.kube.msbarbieri.dev/
                        description: ArgoCD
                        icon: https://miro.medium.com/v2/resize:fit:1400/1*d_nWfpG-EF831-yXwx64HQ.png
                        app: argocd-server
                        namespace: argocd
                - Colmeia:
                    - Prod:
                        href: https://app.colmeia.cx
                        icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAWhjRQakc99Hy6lv9K9NZherllnMNZLpZWw&s
                        description: Prod Colmeia
                        siteMonitor: https://api.colmeia.cx/v1/health-check
                    - Beta:
                        href: https://beta-app.colmeia.cx
                        icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAWhjRQakc99Hy6lv9K9NZherllnMNZLpZWw&s
                        description: Prod Colmeia
                        siteMonitor: https://beta-api.colmeia.cx/v1/health-check
                    - QA:
                        href: https://qa-app.colmeia.cx
                        icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAWhjRQakc99Hy6lv9K9NZherllnMNZLpZWw&s
                        description: QA Colmeia
                        siteMonitor: https://qa-api.colmeia.cx/v1/health-check
                    - Dev:
                        href: https://dev-app.colmeia.cx
                        icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAWhjRQakc99Hy6lv9K9NZherllnMNZLpZWw&s
                        description: Dev Colmeia
                        siteMonitor: https://dev-api.colmeia.cx/v1/health-check
                    - Gitlab:
                        href: http://gitlab.colmeia.me/
                        icon: https://static-00.iconduck.com/assets.00/gitlab-icon-2048x1885-1o0cwkbx.png
                        description: gitlab da colmeia
                        siteMonitor: http://gitlab.colmeia.me/
                    - Grafana:
                        href: https://grafana.colmeia.cx/
                        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Grafana_icon.svg/1969px-Grafana_icon.svg.png
                        description: Colmeia Grafana
                        siteMonitor: http://grafana.colmeia.cx/
                - Colmeia Management:
                    - GCP:
                        href: https://console.cloud.google.com/
                        description: console de gcp
                    - Equinix:
                        href: https://auth.equinix.com/
                        description Equinix
                - Colmeia Admin:
                    - Google Admin:
                        href: https://admin.google.com/
                        description: admin google
                    - Microsoft Admin:
                        href: https://admin.microsoft.com/
                        description: admin microsoft
              widgets:
                # show the kubernetes widget, with the cluster summary and individual nodes
                - kubernetes:
                    cluster:
                      show: true
                      cpu: true
                      memory: true
                      showLabel: true
                      label: "cluster"
                    nodes:
                      show: true
                      cpu: true
                      memory: true
                      showLabel: true
                - search:
                    provider: google
                    target: _self
              kubernetes:
                mode: cluster
            # The service account is necessary to allow discovery of other services
            serviceAccount:
              create: true
              name: homepage

            # This enables the service account to access the necessary resources
            enableRbac: true
            ingress:
              main:
                enabled: true
                annotations:
                  traefik.ingress.kubernetes.io/router.entrypoints: websecure
                  traefik.ingress.kubernetes.io/router.tls: 'true'
                  ingress.kubernetes.io/force-ssl-redirect: "true"
                tls:
                  - secretName: istio-cert
                    hosts:
                    -  kube.msbarbieri.dev
                hosts:
                  - host: kube.msbarbieri.dev
                    paths:
                      - path: /
                        pathType: Prefix
