apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
  name: homepage-local
  namespace: default
spec:
  gateways:
    - default/dns-secure-gateway
  hosts:
    - "kube.msbarbieri.dev"
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      route:
        - destination:
            host: local-homepage.default.svc.cluster.local
            port: 
              number: 3000
