ingress:
  enabled: true
  path: /
  hosts:
    -  kube.msbarbieri.dev
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  labels: {}
  tls:
    - secretName: istio-cert
      hosts:
      -  kube.msbarbieri.dev
