apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: postgres-application-set
  namespace: argocd
spec:
  template:
    metadata:
      name: '{{cluster}}-postgres'
    spec:
      source:
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 12.1.6
        chart: postgresql
        helm:
          parameters:
          - name: global.postgresql.auth.database
            value: '{{cluster}}'
          - name: global.postgresql.auth.username
            value: admin
          - name: global.postgresql.auth.password
            value: admin
          - name: auth.postgresPassword
            value: admin
          - name: global.storageClass
            value: standard
