apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: postgres-application-set
  namespace: argocd
spec:
  template:
    metadata:
      name: '{{cluster}}-redis'
    spec:
      source:
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 17.4.3 
        chart: redis
