apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homepage-application-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        namespace: default
  template:
    metadata:
      labels:
        general: application-sets
        applicationName: homepage
    spec:
      project: default
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
            - Replace=true
        applicationsSync: create-update
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        retry:
          limit: 2
          backoff: 
            duration: 5s
            factor: 2
            maxDuration: 3m0s
