apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kafka-application-set
  namespace: argocd
spec:
  template:
    metadata:
      name: '{{cluster}}-kafka'
    spec:
      source:
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 20.0.4 
        chart: kafka
