
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pgadmin-gateway-application-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        namespace: postgres 
      # other clusters
      # - cluster: engineering-prod
      #   url: https://2.4.6.8
      # - cluster: finance-preprod
      #   url: https://9.8.7.6
  template:
    metadata:
      labels:
        general: application-sets
        all: "true"
        type: gateway
        applicationName: pgadmin
    spec:
      project: default
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2
          backoff: 
            duration: 5s
            factor: 2
            maxDuration: 3m0s
