apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: emqx-application-set
  namespace: argocd
spec:
  template:
    metadata:
      name: '{{cluster}}-emqx'
    spec:
      source:
        repoURL: https://repos.emqx.io/charts
        targetRevision: 5.0.14 
        chart: emqx
